version: "2"
services:
  es:
    image: elasticsearch:2.3
    container_name: es
    networks:
      - foodtrucks
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    networks:
      - foodtrucks
    depends_on:
      - es
networks:
  foodtrucks:
